import streamlit as st
from ui import configure_page, render_sidebar, render_header
from storage import list_reports, read_report

configure_page(); render_sidebar()
render_header("Reports", "Review Markdown reports generated by this app.")
reports = list_reports()
if not reports:
    st.info("No reports yet.")
for path in reports:
    with st.expander(path.name):
        content = read_report(path)
        st.markdown(content)
        st.download_button("Download", content, path.name, "text/markdown", key=f"dl-{path.name}")
